openapi: 3.0.0
info:
  title: Cluster Agent API
  description: Cluster Agent API
  contact:
    email: katepangliu@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/katepangLiu/clusteragent/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: nodeagent
  description: Operations available to nodeagent
paths:
  /tags/pod/{nodeName}:
    get:
      tags:
      - nodeagent
      summary: list services
      description: |
        List all services in the node or in the cluster
      operationId: getPodMetadataForNode
      parameters:
      - name: nodeName
        in: path
        description: k8s nodename
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: List all services in the node or in the cluster
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamespacesPodsStringsSet'
        "400":
          description: bad input parameter
  /tags/pod/{nodeName}/{ns}/{podName}:
    get:
      tags:
      - nodeagent
      summary: list services
      description: |
        List all services in the node
      operationId: getPodMetadata
      parameters:
      - name: nodeName
        in: path
        description: k8s nodename
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: ns
        in: path
        description: k8s namespace
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: podName
        in: path
        description: k8s pod name
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: List all services in the pod
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PodsStringsSet'
        "400":
          description: bad input parameter
components:
  schemas:
    NamespacesPodsStringsSet:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/PodsStringsSet'
      example: namespace-treafik
      x-schema-name: NamespacesPodsStringsSet
    PodsStringsSet:
      type: object
      additionalProperties:
        type: string
        example: traefik
      example: pod-traefik
      x-schema-name: PodsStringsSet
