openapi: 3.0.0
info:
  title: Cluster Agent API
  description: Cluster Agent API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/katepangLiu/clusteragent/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: nodeagent
  description: Operations available to nodeagent
paths:
  /tags/pod/{nodeName}/{ns}/{podName}:
    get:
      tags:
      - nodeagent
      summary: list services
      description: |
        Get Pod Metadata
      operationId: getPodMetadata
      parameters:
      - name: nodeName
        in: path
        description: k8s nodename
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: ns
        in: path
        description: k8s namespace
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: podName
        in: path
        description: k8s pod name
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: List all services in the node or in the cluster
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pod'
                x-content-type: application/json
        "400":
          description: bad input parameter
  /tags/pod/{nodeName}:
    get:
      tags:
      - nodeagent
      summary: list services
      description: |
        List all services in the node or in the cluster
      operationId: getPodMetadataForNode
      parameters:
      - name: nodeName
        in: path
        description: k8s nodename
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: List all services in the node or in the cluster
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NS'
                x-content-type: application/json
        "400":
          description: bad input parameter
components:
  schemas:
    NS:
      required:
      - ns
      - pods
      type: object
      properties:
        ns:
          type: string
          example: default
        pods:
          type: array
          items:
            $ref: '#/components/schemas/Pod'
      example:
        ns: default
        pods:
        - podName: "[\"traefik-kfnda6\"]"
          services:
          - "[\"traefik\",\"traefik-metrics\"]"
          - "[\"traefik\",\"traefik-metrics\"]"
        - podName: "[\"traefik-kfnda6\"]"
          services:
          - "[\"traefik\",\"traefik-metrics\"]"
          - "[\"traefik\",\"traefik-metrics\"]"
    Pod:
      required:
      - podName
      - tags
      type: object
      properties:
        podName:
          type: string
          example: "[\"traefik-kfnda6\"]"
        services:
          type: array
          items:
            $ref: '#/components/schemas/service'
      example:
        podName: "[\"traefik-kfnda6\"]"
        services:
        - "[\"traefik\",\"traefik-metrics\"]"
        - "[\"traefik\",\"traefik-metrics\"]"
    service:
      type: string
      example: "[\"traefik\",\"traefik-metrics\"]"
